language: node_js
node_js:
  - "14"
install:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master
